In [48]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score

In [49]:
y_true = [
    [1, 3, 1, 0, 0],
    [1, 3, 1, 0, 0],
    [1, 3, 1, 0, 0],
    [1, 4, 1, 0, 0],
    [1, 4, 1, 0, 0],
    [1, 4, 1, 0, 0],
    [1, 4, 1, 0, 0],
    [1, 7, 2, 1, 0],
    [1, 7, 2, 1, 0],
    [1, 7, 2, 1, 0]
]
y_true = np.ravel(y_true)
y_true

array([1, 3, 1, 0, 0, 1, 3, 1, 0, 0, 1, 3, 1, 0, 0, 1, 4, 1, 0, 0, 1, 4,
       1, 0, 0, 1, 4, 1, 0, 0, 1, 4, 1, 0, 0, 1, 7, 2, 1, 0, 1, 7, 2, 1,
       0, 1, 7, 2, 1, 0])

In [50]:
y_pred = [
    [0, 2, 0, 0, 1],
    [0, 2, 0, 0, 1],
    [0, 2, 0, 0, 2],
    [0, 4, 0, 0, 0],
    [0, 4, 0, 0, 0],
    [0, 4, 0, 0, 0],
    [0, 4, 0, 0, 0],
    [1, 4, 0, 0, 1],
    [0, 4, 1, 0, 0],
    [1, 4, 1, 0, 0]
]
y_pred = np.ravel(y_pred)
y_pred

array([0, 2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 2, 0, 0, 2, 0, 4, 0, 0, 0, 0, 4,
       0, 0, 0, 0, 4, 0, 0, 0, 0, 4, 0, 0, 0, 1, 4, 0, 0, 1, 0, 4, 1, 0,
       0, 1, 4, 1, 0, 0])

In [51]:
cm = confusion_matrix(y_true, y_pred)
cm

array([[13,  3,  1,  0,  0,  0],
       [18,  2,  0,  0,  0,  0],
       [ 1,  2,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  3,  0]], dtype=int64)

In [52]:
target_names = np.array(['Swipe_machine', 'Product', 'Person', 'Head', 'Background'])
classification_rep = classification_report(y_true, y_pred)

print("\nClassification Report:")
print(classification_rep)


Classification Report:
              precision    recall  f1-score   support

           0       0.41      0.76      0.53        17
           1       0.29      0.10      0.15        20
           2       0.00      0.00      0.00         3
           3       0.00      0.00      0.00         3
           4       0.57      1.00      0.73         4
           7       0.00      0.00      0.00         3

    accuracy                           0.38        50
   macro avg       0.21      0.31      0.23        50
weighted avg       0.30      0.38      0.30        50



C:\Users\prana\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\prana\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\prana\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

In [ ]:
accuracy = accuracy_score(y_true, y_pred)
print('Accuracy:', accuracy)

In [ ]:
precision = precision_score(y_true, y_pred)
print('Precision:', precision)

In [ ]:
recall = recall_score(y_true, y_pred)
print('Recall:', recall)

In [ ]:
f1_score = f1_score(y_true, y_pred)
print('F1 score:', f1_score)